# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/37dc0db9-10b2-4f3b-9b0e-378a52936406";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5258c66d-4b04-4f7a-a0ac-f1fe275d1328".device = "/dev/disk/by-uuid/5258c66d-4b04-4f7a-a0ac-f1fe275d1328";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2988-686D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/370d1d70-62e3-4b8c-af9d-e3c9d1c7f84a";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-542aa02d-d5ff-45c9-a70c-4aee718c6773".device = "/dev/disk/by-uuid/542aa02d-d5ff-45c9-a70c-4aee718c6773";

  swapDevices = [
    {device = "/dev/disk/by-uuid/481fe379-4ae0-4a58-9429-1615d8e1d16e";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
